chat/urls.py
from django.urls import path
from .views import signup_view, home, chat, Group, fileUp, leaveGroup, kickUser, upload_file_chunk, logout_view
from django.contrib.auth import views as auth_views

app_name = 'chat'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', logout_view, name="logout"),
    path('', home, name="home"),
    path('Group/', Group, name="Group"),
    path('room/<str:room_name>', chat, name="chat_room"),
    path('kickuser/<int:id>', kickUser, name="kickUser"),
    path('leave/', leaveGroup, name="leaveGroup"),
    path('signup/', signup_view, name="signup"),
    path('fileUp/', fileUp, name="fileUp"),
    path('file_upload_chunks/', upload_file_chunk, name="file_upload_chunks"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/',include('chat.urls', namespace="chat")),
    path('', lambda request: redirect('/chat/')),
    path('login/', lambda request: redirect('/chat/login/')),
    path('signup/', lambda request: redirect('/chat/signup/')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import random
import string
import os
from django.dispatch import receiver
# Create your models here.

class Room (models.Model):
    name = models.CharField("Room Name", null= False, blank=False, max_length=255)
    description = models.TextField("Description", null=False, blank=False)
    image = models.ImageField("Image", upload_to="images")
    invite = models.CharField("Invite Link", max_length=255)
    slug = models.SlugField(unique=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField("created at", auto_now_add=True, blank=True)
    updated_at = models.DateTimeField("updated at", auto_now=True, blank=True)
    
    def save(self, *args, **kwargs):
        self.invite = ''.join(random.choices(string.ascii_uppercase +
                             string.digits, k=10))
        if not self.invite:
            qs_exists = Room.objects.filter(invite=self.invite).exists()
            while(qs_exists):
                if qs_exists:
                    new_invite = ''.join(random.choices(string.ascii_uppercase +
                             string.digits, k=10))
                self.invite = new_invite
                qs_exists = Room.objects.filter(invite=self.invite).exists()
                
        if not self.slug:
            self.slug = slugify(self.name)
            qs_exists = Room.objects.filter(slug=self.slug).exists()
            while(qs_exists):
                if qs_exists:
                    new_slug = "{slug}-{randstr}".format(
                        slug=self.slug,
                        randstr=random.randint(0, 10000)
                    )
                self.slug = slugify(new_slug)
                qs_exists = Room.objects.filter(slug=self.slug).exists()
        super(Room, self).save(*args, **kwargs)

class Chat (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField("Message", null=True, blank=True)
    file = models.FileField(upload_to='files', null=True, blank=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    isEdited = models.BooleanField("Is Edited ?",default=False)
    created_at = models.DateTimeField("created at", auto_now_add=True, blank=True)
    updated_at = models.DateTimeField("updated at", auto_now=True, blank=True)

@receiver(models.signals.post_delete, sender=Chat)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)
    
class UsersPerRoom(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    created_at = models.DateTimeField("created at", auto_now_add=True, blank=True)
    updated_at = models.DateTimeField("updated at", auto_now=True, blank=True)

class Status(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)
    status = models.BooleanField("Stauts", default=False)
    last_seen = models.DateTimeField("updated at", auto_now=True, blank=True)

chat/forms.py
from django import forms

class InvitationForm(forms.Form):
    invitation = forms.CharField(label="Invitaion Code", max_length=255)
    
class CreateGroup(forms.Form):
    name = forms.CharField(label="Group Name", max_length=255)
    description = forms.CharField(widget=forms.Textarea(attrs={"rows":"5"}))
    groupimage = forms.ImageField()
    
class fileUploads(forms.Form):
    userFile = forms.FileField()

chat/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from chat.models import Chat, Room, UsersPerRoom, Status, User
from .forms import InvitationForm, CreateGroup, fileUploads
from django.contrib import messages
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
import os
import shutil
from django.core.files import File
from .templatetags.filename import filename as FileName
from django.contrib.auth import logout
import os
import signal
from django.db.utils import OperationalError
import sys

if 'runserver' in sys.argv:
    try:
        systemUser = User.objects.get(username = "system", is_superuser = True)
    except User.DoesNotExist:
        # Print message in red color
        print("\033[91mcreate superuser named system then runserver.\033[0m")
        # Send Ctrl+C signal
        os.kill(os.getpid(), signal.SIGINT)
    except OperationalError as e:
        print("\033[91mfirst Migrate all table and create superuser named system then runserver.\033[0m")
        os.kill(os.getpid(), signal.SIGINT)

   
channel_layer = get_channel_layer()

def signup_view(request):
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('chat:login'))
    return render(request,'signup.html',{'form':form})

@login_required
def home(request):
    form = InvitationForm(request.POST or None)
    rooms = UsersPerRoom.objects.filter(user = request.user)
    if form.is_valid():
        data = form.cleaned_data
        # OBQBEKL47M
        try:
            roomobj = Room.objects.get(invite = data['invitation'])
            UsersPerRoomData, created = UsersPerRoom.objects.get_or_create(user = request.user, room = roomobj)
            if created:
                messages.success(request, "Join Successfully!", "alert-success")
                message = f"{request.user.username} Join the Group."
                chatobj = Chat(user = systemUser, message = message, room = roomobj)
                chatobj.save()
                async_to_sync(channel_layer.group_send)(f"{roomobj.slug}_group",{"type":"system_message", "message":{"text":message, "type": "join_group"}, "username": request.user.username, "userid": request.user.id})
            else:
                messages.success(request, "You Already In Group! ", "alert-info")
        except Room.DoesNotExist:
            messages.warning(request, "It's Look-like Invitaion expired!", "alert-warning")
        except Exception as e:
            messages.error(request,"Something went Wrong!","alert-danger")
        return redirect(reverse_lazy('chat:home'))
    return render(request, 'home.html', {"chat": chat, "form": form, "rooms": rooms})

@login_required
def chat(request, room_name):
    try:
        roomobj = Room.objects.get(slug = room_name)
    except Room.DoesNotExist:
        messages.error(request, "Room Does Not Exists!", "alert-warning")
        return redirect(reverse_lazy('chat:home'))
    userChk = UsersPerRoom.objects.filter(room = roomobj, user = request.user).exists()
    # Get the users in a particular room
    users_in_room = User.objects.filter(usersperroom__room=roomobj)

    # Get the status of each user in the room
    userStatus = Status.objects.filter(user__in=users_in_room).order_by("-status").exclude(user = request.user)

    if not userChk:
        messages.info(request, "First Join Group using Invitation link.", "alert-primary")
        return redirect(reverse_lazy('chat:home')) 
    chat = Chat.objects.filter(room = roomobj)
    return render(request, 'chat.html', {"chat": chat, "room_name":room_name, "roomobj": roomobj, "userStatus": userStatus})

@login_required
@require_http_methods(["POST"])
def Group(request):
    form = CreateGroup(request.POST, request.FILES)
    if form.is_valid():
        data = form.cleaned_data
        roomobj = Room(name=data.get('name'), description = data.get('description'), image = data.get('groupimage'),created_by=request.user)
        roomobj.save()
        UsersPerRoomData = UsersPerRoom(user = request.user, room= roomobj)
        UsersPerRoomData.save()
        messages.success(request,"Group Created Successfully ^_^","alert-success")
    else:
        print(form.errors)
        messages.error(request,"Something went Wrong!","alert-danger")
    return redirect(reverse_lazy('chat:home'))

@login_required
@require_http_methods(["POST"])
@csrf_exempt
def fileUp(request):
    form = fileUploads(request.POST,request.FILES)
    if form.is_valid():
        data = form.cleaned_data
        print(request.FILES['userFile'].content_type)
        group_name = request.headers['Referer'].split("/")[-1]
        roomobj = Room.objects.get(slug = group_name)
        chatobj = Chat(user = request.user, room = roomobj, file = data['userFile'])
        chatobj.save()
        async_to_sync(channel_layer.group_send)(f"{group_name}_group", {"type": "chat_file_completed", "file_name":f'{request.FILES["userFile"].name}', "file_type" : f'{request.FILES["userFile"].content_type}', "id": chatobj.id, "username":request.user.username, "url":str(chatobj.file)})

    else:
        print(form.errors)
        return JsonResponse({"status":"fail"}, status = 400)
    return JsonResponse({"status":"success"},status=200)

async def upload_file_chunk(request):
    file = request.FILES.get('chunk')
    total_chunks = int(request.POST.get('totalChunks'))
    chunk_index = int(request.POST.get('chunkIndex'))

    # Extract the file ID from the request
    file_id = request.POST.get('fileId')
    print(total_chunks, chunk_index)
    filename = request.POST.get('filename')
    upload_dir = os.path.join('uploads/files', file_id)

    # Create the upload directory if it doesn't exist
    if not os.path.exists(upload_dir):
        os.makedirs(upload_dir)

    # Build the path to the chunk file
    chunk_name = f'{filename}.part{chunk_index}'
    chunk_path = os.path.join(upload_dir, chunk_name)

    # Save the chunk data to a file
    with open(chunk_path, 'wb') as f:
        f.write(file.read())

    # Check if all chunks have been uploaded
    if chunk_index == total_chunks - 1:
        # Combine the chunks into the final file
        final_path = os.path.join(upload_dir, filename)
        with open(final_path, 'wb') as f:
            for i in range(total_chunks):
                chunk_name = f'{filename}.part{i}'
                chunk_path = os.path.join(upload_dir, chunk_name)
                with open(chunk_path, 'rb') as chunk_file:
                    f.write(chunk_file.read())
                
        # Delete the chunk files
        for i in range(total_chunks):
            chunk_name = f'{filename}.part{i}'
            chunk_path = os.path.join(upload_dir, chunk_name)
            os.remove(chunk_path)
        
        with open(final_path, 'rb') as f:
            group_name = request.headers['Referer'].split("/")[-1]
            roomobj = await Room.objects.aget(slug = group_name)
            chatobj = await Chat.objects.acreate(user = request.user, room = roomobj, file = File(f, name=filename))

        shutil.rmtree(upload_dir)
        await channel_layer.group_send(f"{group_name}_group", {"type": "chat_file_completed", "file_name":f'{FileName(chatobj.file)}', "id": chatobj.id, "username":request.user.username, "url":str(chatobj.file)})
        return JsonResponse({'success': True})

    return JsonResponse({'success': False})

# async def upload_file_chunk(request):
#     file = request.FILES.get('chunk')
#     total_chunks = int(request.POST.get('totalChunks'))
#     chunk_index = int(request.POST.get('chunkIndex'))

#     # Extract the file ID from the request
#     file_id = request.POST.get('fileId')
#     print(total_chunks, chunk_index)
#     filename = request.POST.get('filename')
#     upload_dir = os.path.join('uploads/files', file_id)

#     # Create the upload directory if it doesn't exist
#     if not os.path.exists(upload_dir):
#         os.makedirs(upload_dir)

#     # Build the path to the chunk file
#     chunk_name = f'{filename}.part{chunk_index}'
#     chunk_path = os.path.join(upload_dir, chunk_name)

#     # Save the chunk data to a file
#     with open(chunk_path, 'wb') as f:
#         f.write(file.read())

#     # Check if all chunks have been uploaded
#     if chunk_index == total_chunks - 1:
#         # Combine the chunks into the final file
#         final_path = os.path.join(os.path.dirname(upload_dir), filename)
#         with open(final_path, 'wb') as f:
#             for i in range(total_chunks):
#                 chunk_name = f'{filename}.part{i}'
#                 chunk_path = os.path.join(upload_dir, chunk_name)
#                 with open(chunk_path, 'rb') as chunk_file:
#                     f.write(chunk_file.read())

#         # Delete the chunk files
#         # for i in range(total_chunks):
#         #     chunk_name = f'{filename}.part{i}'
#         #     chunk_path = os.path.join(upload_dir, chunk_name)
#         #     os.remove(chunk_path)
#         # os.rmdir(upload_dir)
#         shutil.rmtree(upload_dir)

#         return JsonResponse({'success': True})

#     return JsonResponse({'success': False})

@login_required
def leaveGroup(request):
    user = request.user
    try:
        room_name = request.headers['Referer'].split("/")[-1]
        roomChk = Room.objects.get(slug = room_name)
        userChk = UsersPerRoom.objects.get(user = user, room = roomChk)
        userChk.delete()
        message = f"{user.username} Left the Group."
        chatobj = Chat(user = systemUser, message = message, room = roomChk)
        chatobj.save()

chat/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            title
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block styleContainer%}

    {% endblock %}
</head>

<body>
    <div class="bg">
        <div class="login-container">
    {% block content %}
    <!-- default content text (typically empty) -->
    {% endblock %}
        </div>
        </div>
</body>

</html>

chat/templates/home.html
{% include 'navbar.html' %}
{% load static %}
{% block styleContainer %}
{% endblock styleContainer %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
{% block content %}
<div class="p-2 ">

  {% if messages %}
  {% for message in messages %}
  <div {% if message.tags %} class="alert {{ message.tags }}" {% else %} class="alert alert-primary" {% endif %}
    role="alert">
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}

  <span role="button" id="createGroup" class="float" data-bs-toggle="modal" data-bs-target="#exampleModal"
    onclick="openModal(this.id)">
    <i class="fa fa-plus my-float"></i>
  </span>
  <span role="button" id="inviteLink" class="float2" data-bs-toggle="modal" data-bs-target="#exampleModal"
    onclick="openModal(this.id)">
    <i class="fa fa-link my-float"></i>
  </span>
  <div id="cards_landscape_wrap-2">
    <div class="p-2">
        <div class="row">
          {% for room in rooms.all %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <a href="{% url 'chat:chat_room' room_name=room.room.slug%}">
                    <div class="card-flyer">
                        <div class="text-box">
                            <div class="image-box">
                                <img src="{% get_media_prefix %}{{room.room.image}}" alt="" />
                            </div>
                            <div class="text-container">
                                <h6 class="text-center">{{room.room.name}}</h6>
                                <p >{{room.room.description}}</p>
                            </div>
                            <span class="list-group-item">InviteCode - {{room.room.invite}}</span>                      
                            <div class="card-footer">                           
                              <small class="text-muted">Created By {% if room.room.created_by %} {{room.room.created_by}} {% else %} Unknown {% endif %}</small>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
            {% comment "" %}<button onclick="notifyMe()">Notify me!</button>{% endcomment %}
        </div>
    </div>
</div>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="modal-title">Have an Invitation ?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div>
          <div class="modal-body" id="modal-body">
            <form method="post">
              {% csrf_token %}
              <div class="mb-3">
                <label for="invitaionid" class="form-label">{{form.invitation.label}}</label>
                <input type="text" class="form-control" id="invitaionid" name="{{form.invitation.name}}">
              </div>
          </div>
          <div class="modal-footer" id="modal-footer">

          </div>
          
          </form>
        </div>
      </div>
    </div>
  </div>

  <script>
    function openModal(id = "") {
      let modalBody = document.getElementById("modal-body");
      let modalTitle = document.getElementById("modal-title");
      let modalFooter = document.getElementById("modal-footer");
      if (id.toLowerCase() === "creategroup") {
        modalTitle.innerHTML = "New Group";
        modalBody.innerHTML = `
      <form method="post" action="{% url 'chat:Group' %}" id ="${id}form" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="mb-3">
          <label for="groupname" class="form-label">Group Name</label>
          <input type="text" class="form-control" id="groupname" name="name">
        </div>
        <div class="mb-3">
          <label for="groupdescription" class="form-label">Group Description</label>
          <textarea class="form-control" id="groupdescription" name="description"></textarea>
        </div>
        <div class="mb-3">
          <label for="groupimage" class="form-label">Group Image</label>
          <input type="file" class="form-control" id="groupimage" name="groupimage">
        </div>
      `;
        modalFooter.innerHTML = `
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-primary" onclick="formSubmmiter('${id}')">Create</button>
      `;
      }
      else {
        modalTitle.innerHTML = "Have an Invitation ?";
        modalBody.innerHTML = `
      <form method="post" id ="${id}form">
        {% csrf_token %}
        <div class="mb-3">
          <label for="invitaionid" class="form-label">{{form.invitation.label}}</label>
          <input type="text" class="form-control" id="invitaionid" name="{{form.invitation.name}}">
        </div>
      `;
        modalFooter.innerHTML = `
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-primary" onclick="formSubmmiter('${id}')">Join</button>
      `;
      }
    }

    function formSubmmiter(id) {
      let form = document.getElementById(`${id}form`).submit();
    }
    function notifyMe() {
      if (!("Notification" in window)) {
        // Check if the browser supports notifications
        alert("This browser does not support desktop notification");
      } else if (Notification.permission === "granted") {
        // Check whether notification permissions have already been granted;
        // if so, create a notification
        const notification = new Notification("Hi there!");
        // …
      } else if (Notification.permission !== "denied") {
        // We need to ask the user for permission
        Notification.requestPermission().then((permission) => {
          // If the user accepts, let's create a notification
          if (permission === "granted") {
            const notification = new Notification("Hi there!");
            // …
          }
        });
      }
    
      // At last, if the user has denied notifications, and you
      // want to be respectful there is no need to bother them anymore.
    }
  </script>
  {% endblock content %}

chat/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light custom-navclass">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" id = "menubtn">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Chat</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'chat:logout' %}">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
</body>
</html>

chat/templates/signup.html
{% extends 'base.html' %}

{% block title %}
Signup
{% endblock title %}
{% load static %}
{% block styleContainer %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}

<form method="post" class="fromdiv">
    {% csrf_token %}
        <h1>Signup</h1>
        <div class="form-group mt-2">
            <label for="{{form.username.name}}">{{form.username.label}}</label>
            <input type="text" class="form-control" name="{{form.username.name}}" id="{{form.username.name}}" title="{{ form.username.help_text}}" placeholder="Demo123">
            {% if form.username.errors %}
                <small>{{form.username.errors}}</small>
            {% endif %}
        </div>
        <div class="form-group mt-2">
            <label for="{{form.password1.name}}">{{form.password1.label}}</label>
            <input type="password" class="form-control" name="{{form.password1.name}}" id="{{form.password1.name}}" title="{{form.password1.help_text}}" placeholder="1234">
        </div>
        {% if form.password1.errors %}
            <small>{{form.password1.errors}}</small>
        {% endif %}
        <div class="form-group mt-2">
            <label for="{{form.password2.name}}">{{form.password2.label}}</label>
            <input type="password" class="form-control" name="{{form.password2.name}}" id="{{form.password2.name}}" placeholder="1234">
        </div>
        {% if form.password2.errors %}
            <small>{{form.password2.errors}}</small>
        {% endif %}
        <input type="submit" class="btn btn-primary mt-2" value="Signup">
        <p>Already have an Account? <a href="{% url 'chat:login' %}" class="loginsignup-a">Login</a></p>
</form>

{% endblock content %}